# Generated by Django 4.2.7 on 2023-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('address', models.EmailField(max_length=50)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='img')),
                ('createat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
